// <auto-generated />
using BusinessApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinesssApi.Migrations
{
    [DbContext(typeof(BusinessApiContext))]
    [Migration("20230211090222_AddModelValidation")]
    partial class AddModelValidation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BusinessApi.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<string>("Review")
                        .HasColumnType("longtext");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Address = "123 Moole Street",
                            Description = "Fancy american restaurant",
                            Name = "Starz Restaurant",
                            Rating = 4.5999999999999996,
                            Review = "Pricy and need to make reservations"
                        },
                        new
                        {
                            BusinessId = 2,
                            Address = "124 Moole Street",
                            Description = "Antique bookstore",
                            Name = "Rexie's Bookstore",
                            Rating = 3.1000000000000001,
                            Review = "Not a lot of books"
                        },
                        new
                        {
                            BusinessId = 3,
                            Address = "125 Moole Street",
                            Description = "Local handmande jewlery shop",
                            Name = "Matilda Jewlers",
                            Rating = 5.0,
                            Review = "Has a variety of jewlery and can customize"
                        },
                        new
                        {
                            BusinessId = 4,
                            Address = "126 Moole Street",
                            Description = "Unique ice cream flavor shop",
                            Name = "Pip's Ice Cream",
                            Rating = 4.0999999999999996,
                            Review = "Can try all flavors"
                        },
                        new
                        {
                            BusinessId = 5,
                            Address = "127 Moole Street",
                            Description = "Pet Shop",
                            Name = "Over the Sea",
                            Rating = 2.5,
                            Review = "Employee don't help out"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
